name: Rolling Restart

on:
  push:
    branches:
      - main  # Replace with the desired branch

jobs:
  trigger_rolling_restart:
    runs-on: ubuntu-latest

    steps:
      - uses: Azure/k8s-deploy@v4
      with:
        resource-group: yourResourceGroup
        name: yourClusterName
        action: deploy
        strategy: basic

        private-cluster: true
        manifests: |
            manifests/app.deployment.yaml
        images: |
            registry.azurecr.io/containername

