name: Rolling Restart

on:
  push:
    branches:
      - main  # Replace with the desired branch

jobs:
  trigger_rolling_restart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This action will clone your repository into the workspace

      - name: List Workspace Contents
        run: |
          ls -R

      - name: Set Kubernetes Context
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - uses: Azure/k8s-deploy@v4
        with:
          resource-group: yourResourceGroup
          name: yourClusterName
          action: deploy
          strategy: basic
          private-cluster: true
          manifests: |
            manifests/app.deployment.yaml  # Corrected file path
          images: |
            sorinmatei/tf-app:latest
