name: Deploy to Kubernetes

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install gke-gcloud-auth-plugin
      run: |
        sudo apt-get install kubectl
        gcloud components install kubectl

    - name: Create kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > $HOME/.kube/config

    - name: Print kubeconfig contents
      run: cat $HOME/.kube/config

    - name: Use context
      run: kubectl get pods --kubeconfig=$HOME/.kube/config

    - name: Deploy to K8s
      run: kubectl apply -f manifests/
